### ISSUE TITLE
Prompt typing area is partly obscured by horizontal scroll bar

### ISSUE THREAD

**Issue by paul-e-allen** [CU-CommunityApps/ct-azure-openai-gpt4-chat#280]
Not a big deal, but the default size of the prompt typing area is consistently too small, on both Chrome and FireFox. Even though the default seems to be exactly the size of a single line of text (which is fine), the horizontal scroll bar makes makes it difficult to see everything one is typing.

![prompt-area](https://github.com/CU-CommunityApps/ct-azure-openai-gpt4-chat/assets/13118967/10478d9c-7bc4-4dfc-8632-751bb0315c79)

Maybe just a little more buffer around the line would make the text more visible?

**Comment by mikesprague** [comment]
As of yet, I have been unable to replicate this (using Edge, Chrome, Firefox, or Safari) and that's making it a little hard to determine the correct style updates. I am going to see if I can get 30 mins on the calendar next week for us to look at this together briefly.

**Comment by mikesprague** [comment]
Explicitly setting the horizontal scrollbar on the `textarea` not to display (via `overflow-y: hidden`) in an attempt to solve this. Should go out in next release.

**Comment by mikesprague** [comment]
I just did a manual deploy from `main` with the latest changes. In theory, next time you use the app and reload you should be on `v0.21.1` with this change in place and we'll know if it improved anything or not.

**Comment by paul-e-allen** [comment]
I'm looking at `v0.21.1` and can confirm that this seems to have fixed the problem for me.

**Comment by mikesprague** [comment]
Thanks for confirming!
